name: Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pull-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username:  ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'deordie-bot'
          images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}'
